package test3.ncxchile.cl.greenDAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import test3.ncxchile.cl.greenDAO.Autoridad;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table autoridad.
*/
public class AutoridadDao extends AbstractDao<Autoridad, Long> {

    public static final String TABLENAME = "autoridad";

    /**
     * Properties of entity Autoridad.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cargo = new Property(1, String.class, "cargo", false, "CARGO");
        public final static Property Institucion = new Property(2, String.class, "institucion", false, "INSTITUCION");
        public final static Property UnidadPolicial = new Property(3, String.class, "unidadPolicial", false, "UNIDAD_POLICIAL");
        public final static Property NumeroFuncionario = new Property(4, String.class, "numeroFuncionario", false, "NUMERO_FUNCIONARIO");
        public final static Property PersonaID = new Property(5, long.class, "personaID", false, "PERSONA_ID");
    };

    private DaoSession daoSession;


    public AutoridadDao(DaoConfig config) {
        super(config);
    }
    
    public AutoridadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'autoridad' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CARGO' TEXT," + // 1: cargo
                "'INSTITUCION' TEXT," + // 2: institucion
                "'UNIDAD_POLICIAL' TEXT," + // 3: unidadPolicial
                "'NUMERO_FUNCIONARIO' TEXT," + // 4: numeroFuncionario
                "'PERSONA_ID' INTEGER NOT NULL );"); // 5: personaID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'autoridad'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Autoridad entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cargo = entity.getCargo();
        if (cargo != null) {
            stmt.bindString(2, cargo);
        }
 
        String institucion = entity.getInstitucion();
        if (institucion != null) {
            stmt.bindString(3, institucion);
        }
 
        String unidadPolicial = entity.getUnidadPolicial();
        if (unidadPolicial != null) {
            stmt.bindString(4, unidadPolicial);
        }
 
        String numeroFuncionario = entity.getNumeroFuncionario();
        if (numeroFuncionario != null) {
            stmt.bindString(5, numeroFuncionario);
        }
        stmt.bindLong(6, entity.getPersonaID());
    }

    @Override
    protected void attachEntity(Autoridad entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Autoridad readEntity(Cursor cursor, int offset) {
        Autoridad entity = new Autoridad( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cargo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // institucion
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // unidadPolicial
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // numeroFuncionario
            cursor.getLong(offset + 5) // personaID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Autoridad entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCargo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setInstitucion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUnidadPolicial(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNumeroFuncionario(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPersonaID(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Autoridad entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Autoridad entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPersonaDao().getAllColumns());
            builder.append(" FROM autoridad T");
            builder.append(" LEFT JOIN persona T0 ON T.'PERSONA_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Autoridad loadCurrentDeep(Cursor cursor, boolean lock) {
        Autoridad entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Persona persona = loadCurrentOther(daoSession.getPersonaDao(), cursor, offset);
         if(persona != null) {
            entity.setPersona(persona);
        }

        return entity;    
    }

    public Autoridad loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Autoridad> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Autoridad> list = new ArrayList<Autoridad>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Autoridad> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Autoridad> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
