package test3.ncxchile.cl.greenDAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import test3.ncxchile.cl.greenDAO.Cliente;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table cliente.
*/
public class ClienteDao extends AbstractDao<Cliente, Long> {

    public static final String TABLENAME = "cliente";

    /**
     * Properties of entity Cliente.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Licencia = new Property(1, String.class, "licencia", false, "LICENCIA");
        public final static Property PersonaID = new Property(2, long.class, "personaID", false, "PERSONA_ID");
        public final static Property ClientePropietarioID = new Property(3, long.class, "clientePropietarioID", false, "CLIENTE_PROPIETARIO_ID");
    };

    private DaoSession daoSession;

    private Query<Cliente> vehiculoData_ClientePropietarioQuery;

    public ClienteDao(DaoConfig config) {
        super(config);
    }
    
    public ClienteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'cliente' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'LICENCIA' TEXT," + // 1: licencia
                "'PERSONA_ID' INTEGER NOT NULL ," + // 2: personaID
                "'CLIENTE_PROPIETARIO_ID' INTEGER NOT NULL );"); // 3: clientePropietarioID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'cliente'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Cliente entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String licencia = entity.getLicencia();
        if (licencia != null) {
            stmt.bindString(2, licencia);
        }
        stmt.bindLong(3, entity.getPersonaID());
    }

    @Override
    protected void attachEntity(Cliente entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Cliente readEntity(Cursor cursor, int offset) {
        Cliente entity = new Cliente( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // licencia
            cursor.getLong(offset + 2) // personaID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Cliente entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLicencia(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPersonaID(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Cliente entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Cliente entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "clientePropietario" to-many relationship of VehiculoData. */
    public List<Cliente> _queryVehiculoData_ClientePropietario(long clientePropietarioID) {
        synchronized (this) {
            if (vehiculoData_ClientePropietarioQuery == null) {
                QueryBuilder<Cliente> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ClientePropietarioID.eq(null));
                vehiculoData_ClientePropietarioQuery = queryBuilder.build();
            }
        }
        Query<Cliente> query = vehiculoData_ClientePropietarioQuery.forCurrentThread();
        query.setParameter(0, clientePropietarioID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPersonaDao().getAllColumns());
            builder.append(" FROM cliente T");
            builder.append(" LEFT JOIN persona T0 ON T.'PERSONA_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Cliente loadCurrentDeep(Cursor cursor, boolean lock) {
        Cliente entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Persona persona = loadCurrentOther(daoSession.getPersonaDao(), cursor, offset);
         if(persona != null) {
            entity.setPersona(persona);
        }

        return entity;    
    }

    public Cliente loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Cliente> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Cliente> list = new ArrayList<Cliente>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Cliente> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Cliente> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
