package test3.ncxchile.cl.greenDAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FICHA_ESTADO_VISUAL.
*/
public class FichaEstadoVisualDao extends AbstractDao<FichaEstadoVisual, Long> {

    public static final String TABLENAME = "FICHA_ESTADO_VISUAL";

    /**
     * Properties of entity FichaEstadoVisual.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Valor = new Property(1, Boolean.class, "valor", false, "VALOR");
        public final static Property Observacion = new Property(2, String.class, "observacion", false, "OBSERVACION");
        public final static Property IdVehiculo = new Property(3, long.class, "idVehiculo", false, "ID_VEHICULO");
        public final static Property IdEstadoVisual = new Property(4, long.class, "idEstadoVisual", false, "ID_ESTADO_VISUAL");
    };

    private DaoSession daoSession;

    private Query<FichaEstadoVisual> vehiculo_FichaEstadoVisualQuery;
    private Query<FichaEstadoVisual> estadoVisual_FichaEstadoVisualQuery;

    public FichaEstadoVisualDao(DaoConfig config) {
        super(config);
    }
    
    public FichaEstadoVisualDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FICHA_ESTADO_VISUAL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'VALOR' INTEGER," + // 1: valor
                "'OBSERVACION' TEXT," + // 2: observacion
                "'ID_VEHICULO' INTEGER NOT NULL ," + // 3: idVehiculo
                "'ID_ESTADO_VISUAL' INTEGER NOT NULL );"); // 4: idEstadoVisual
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FICHA_ESTADO_VISUAL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FichaEstadoVisual entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean valor = entity.getValor();
        if (valor != null) {
            stmt.bindLong(2, valor ? 1l: 0l);
        }
 
        String observacion = entity.getObservacion();
        if (observacion != null) {
            stmt.bindString(3, observacion);
        }
        stmt.bindLong(4, entity.getIdVehiculo());
        stmt.bindLong(5, entity.getIdEstadoVisual());
    }

    @Override
    protected void attachEntity(FichaEstadoVisual entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FichaEstadoVisual readEntity(Cursor cursor, int offset) {
        FichaEstadoVisual entity = new FichaEstadoVisual( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // valor
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // observacion
            cursor.getLong(offset + 3), // idVehiculo
            cursor.getLong(offset + 4) // idEstadoVisual
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FichaEstadoVisual entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setValor(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setObservacion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdVehiculo(cursor.getLong(offset + 3));
        entity.setIdEstadoVisual(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FichaEstadoVisual entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FichaEstadoVisual entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "FichaEstadoVisual" to-many relationship of Vehiculo. */
    public List<FichaEstadoVisual> _queryVehiculo_FichaEstadoVisual(long idVehiculo) {
        synchronized (this) {
            if (vehiculo_FichaEstadoVisualQuery == null) {
                QueryBuilder<FichaEstadoVisual> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdVehiculo.eq(null));
                queryBuilder.orderRaw("ID_VEHICULO ASC");
                vehiculo_FichaEstadoVisualQuery = queryBuilder.build();
            }
        }
        Query<FichaEstadoVisual> query = vehiculo_FichaEstadoVisualQuery.forCurrentThread();
        query.setParameter(0, idVehiculo);
        return query.list();
    }

    /** Internal query to resolve the "FichaEstadoVisual" to-many relationship of EstadoVisual. */
    public List<FichaEstadoVisual> _queryEstadoVisual_FichaEstadoVisual(long idEstadoVisual) {
        synchronized (this) {
            if (estadoVisual_FichaEstadoVisualQuery == null) {
                QueryBuilder<FichaEstadoVisual> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdEstadoVisual.eq(null));
                queryBuilder.orderRaw("ID_ESTADO_VISUAL ASC");
                estadoVisual_FichaEstadoVisualQuery = queryBuilder.build();
            }
        }
        Query<FichaEstadoVisual> query = estadoVisual_FichaEstadoVisualQuery.forCurrentThread();
        query.setParameter(0, idEstadoVisual);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getVehiculoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getEstadoVisualDao().getAllColumns());
            builder.append(" FROM FICHA_ESTADO_VISUAL T");
            builder.append(" LEFT JOIN VEHICULO T0 ON T.'ID_VEHICULO'=T0.'_id'");
            builder.append(" LEFT JOIN ESTADO_VISUAL T1 ON T.'ID_ESTADO_VISUAL'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected FichaEstadoVisual loadCurrentDeep(Cursor cursor, boolean lock) {
        FichaEstadoVisual entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Vehiculo vehiculo = loadCurrentOther(daoSession.getVehiculoDao(), cursor, offset);
         if(vehiculo != null) {
            entity.setVehiculo(vehiculo);
        }
        offset += daoSession.getVehiculoDao().getAllColumns().length;

        EstadoVisual estadoVisual = loadCurrentOther(daoSession.getEstadoVisualDao(), cursor, offset);
         if(estadoVisual != null) {
            entity.setEstadoVisual(estadoVisual);
        }

        return entity;    
    }

    public FichaEstadoVisual loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<FichaEstadoVisual> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<FichaEstadoVisual> list = new ArrayList<FichaEstadoVisual>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<FichaEstadoVisual> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<FichaEstadoVisual> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
