package test3.ncxchile.cl.greenDAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import test3.ncxchile.cl.greenDAO.FichaEstadoVisual;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FichaEstadoVisual.
*/
public class FichaEstadoVisualDao extends AbstractDao<FichaEstadoVisual, Long> {

    public static final String TABLENAME = "FichaEstadoVisual";

    /**
     * Properties of entity FichaEstadoVisual.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdFichaEstadoVisual = new Property(1, Integer.class, "idFichaEstadoVisual", false, "ID_FICHA_ESTADO_VISUAL");
        public final static Property IdFicha = new Property(2, Integer.class, "idFicha", false, "ID_FICHA");
        public final static Property Valor = new Property(3, Boolean.class, "valor", false, "VALOR");
        public final static Property Observacion = new Property(4, String.class, "observacion", false, "OBSERVACION");
        public final static Property EstadoVisualID = new Property(5, long.class, "estadoVisualID", false, "ESTADO_VISUAL_ID");
        public final static Property FichaEstadovisualID = new Property(6, long.class, "fichaEstadovisualID", false, "FICHA_ESTADOVISUAL_ID");
    };

    private DaoSession daoSession;

    private Query<FichaEstadoVisual> vehiculo_FichaEstadoVisualListQuery;

    public FichaEstadoVisualDao(DaoConfig config) {
        super(config);
    }
    
    public FichaEstadoVisualDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FichaEstadoVisual' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ID_FICHA_ESTADO_VISUAL' INTEGER," + // 1: idFichaEstadoVisual
                "'ID_FICHA' INTEGER," + // 2: idFicha
                "'VALOR' INTEGER," + // 3: valor
                "'OBSERVACION' TEXT," + // 4: observacion
                "'ESTADO_VISUAL_ID' INTEGER NOT NULL ," + // 5: estadoVisualID
                "'FICHA_ESTADOVISUAL_ID' INTEGER NOT NULL );"); // 6: fichaEstadovisualID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FichaEstadoVisual'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FichaEstadoVisual entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer idFichaEstadoVisual = entity.getIdFichaEstadoVisual();
        if (idFichaEstadoVisual != null) {
            stmt.bindLong(2, idFichaEstadoVisual);
        }
 
        Integer idFicha = entity.getIdFicha();
        if (idFicha != null) {
            stmt.bindLong(3, idFicha);
        }
 
        Boolean valor = entity.getValor();
        if (valor != null) {
            stmt.bindLong(4, valor ? 1l: 0l);
        }
 
        String observacion = entity.getObservacion();
        if (observacion != null) {
            stmt.bindString(5, observacion);
        }
        stmt.bindLong(6, entity.getEstadoVisualID());
    }

    @Override
    protected void attachEntity(FichaEstadoVisual entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FichaEstadoVisual readEntity(Cursor cursor, int offset) {
        FichaEstadoVisual entity = new FichaEstadoVisual( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // idFichaEstadoVisual
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // idFicha
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // valor
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // observacion
            cursor.getLong(offset + 5) // estadoVisualID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FichaEstadoVisual entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdFichaEstadoVisual(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setIdFicha(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setValor(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setObservacion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEstadoVisualID(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FichaEstadoVisual entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FichaEstadoVisual entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "fichaEstadoVisualList" to-many relationship of Vehiculo. */
    public List<FichaEstadoVisual> _queryVehiculo_FichaEstadoVisualList(long fichaEstadovisualID) {
        synchronized (this) {
            if (vehiculo_FichaEstadoVisualListQuery == null) {
                QueryBuilder<FichaEstadoVisual> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FichaEstadovisualID.eq(null));
                vehiculo_FichaEstadoVisualListQuery = queryBuilder.build();
            }
        }
        Query<FichaEstadoVisual> query = vehiculo_FichaEstadoVisualListQuery.forCurrentThread();
        query.setParameter(0, fichaEstadovisualID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEstadoVisualDao().getAllColumns());
            builder.append(" FROM FichaEstadoVisual T");
            builder.append(" LEFT JOIN EstadoVisual T0 ON T.'ESTADO_VISUAL_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected FichaEstadoVisual loadCurrentDeep(Cursor cursor, boolean lock) {
        FichaEstadoVisual entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        EstadoVisual estadoVisual = loadCurrentOther(daoSession.getEstadoVisualDao(), cursor, offset);
         if(estadoVisual != null) {
            entity.setEstadoVisual(estadoVisual);
        }

        return entity;    
    }

    public FichaEstadoVisual loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<FichaEstadoVisual> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<FichaEstadoVisual> list = new ArrayList<FichaEstadoVisual>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<FichaEstadoVisual> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<FichaEstadoVisual> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }

    public Long getNextId(){
        Long id= queryBuilder().count();

        return id+1;
    }
 
}
