package test3.ncxchile.cl.greenDAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import test3.ncxchile.cl.greenDAO.FinalizarActa;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table finalizarActa.
*/
public class FinalizarActaDao extends AbstractDao<FinalizarActa, Long> {

    public static final String TABLENAME = "finalizarActa";

    /**
     * Properties of entity FinalizarActa.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Georef = new Property(1, String.class, "georef", false, "GEOREF");
        public final static Property FirmaAutoridad = new Property(2, String.class, "firmaAutoridad", false, "FIRMA_AUTORIDAD");
        public final static Property FirmaGruero = new Property(3, String.class, "firmaGruero", false, "FIRMA_GRUERO");
        public final static Property ActaID = new Property(4, long.class, "actaID", false, "ACTA_ID");
    };

    private DaoSession daoSession;


    public FinalizarActaDao(DaoConfig config) {
        super(config);
    }
    
    public FinalizarActaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'finalizarActa' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'GEOREF' TEXT," + // 1: georef
                "'FIRMA_AUTORIDAD' TEXT," + // 2: firmaAutoridad
                "'FIRMA_GRUERO' TEXT," + // 3: firmaGruero
                "'ACTA_ID' INTEGER NOT NULL );"); // 4: actaID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'finalizarActa'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FinalizarActa entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String georef = entity.getGeoref();
        if (georef != null) {
            stmt.bindString(2, georef);
        }
 
        String firmaAutoridad = entity.getFirmaAutoridad();
        if (firmaAutoridad != null) {
            stmt.bindString(3, firmaAutoridad);
        }
 
        String firmaGruero = entity.getFirmaGruero();
        if (firmaGruero != null) {
            stmt.bindString(4, firmaGruero);
        }
        stmt.bindLong(5, entity.getActaID());
    }

    @Override
    protected void attachEntity(FinalizarActa entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FinalizarActa readEntity(Cursor cursor, int offset) {
        FinalizarActa entity = new FinalizarActa( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // georef
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // firmaAutoridad
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // firmaGruero
            cursor.getLong(offset + 4) // actaID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FinalizarActa entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGeoref(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFirmaAutoridad(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFirmaGruero(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setActaID(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FinalizarActa entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FinalizarActa entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getActaDao().getAllColumns());
            builder.append(" FROM finalizarActa T");
            builder.append(" LEFT JOIN Acta T0 ON T.'ACTA_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected FinalizarActa loadCurrentDeep(Cursor cursor, boolean lock) {
        FinalizarActa entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Acta acta = loadCurrentOther(daoSession.getActaDao(), cursor, offset);
         if(acta != null) {
            entity.setActa(acta);
        }

        return entity;    
    }

    public FinalizarActa loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<FinalizarActa> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<FinalizarActa> list = new ArrayList<FinalizarActa>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<FinalizarActa> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<FinalizarActa> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
