package test3.ncxchile.cl.greenDAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOGS.
 */
public class Logs {

    private Long id;
    private java.util.Date timeStamp;
    private Float longitud;
    private Float latitud;
    private String Descripcion;

    public Logs() {
    }

    public Logs(Long id) {
        this.id = id;
    }

    public Logs(Long id, java.util.Date timeStamp, Float longitud, Float latitud, String Descripcion) {
        this.id = id;
        this.timeStamp = timeStamp;
        this.longitud = longitud;
        this.latitud = latitud;
        this.Descripcion = Descripcion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(java.util.Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Float getLongitud() {
        return longitud;
    }

    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }

    public Float getLatitud() {
        return latitud;
    }

    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

}
