package test3.ncxchile.cl.greenDAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MAPA.
 */
public class Mapa {

    private Long id;
    private String Mapa;

    public Mapa() {
    }

    public Mapa(Long id) {
        this.id = id;
    }

    public Mapa(Long id, String Mapa) {
        this.id = id;
        this.Mapa = Mapa;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMapa() {
        return Mapa;
    }

    public void setMapa(String Mapa) {
        this.Mapa = Mapa;
    }

}
