package test3.ncxchile.cl.greenDAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ParqueaderoSummary.
 */
public class ParqueaderoSummary {

    private Long id;
    private String nave;
    private Integer numero;
    private Integer numeroEnAgrupador;
    private Integer agrupador;
    private String recinto;
    private Boolean tribunales;
    private String estado;
    private Boolean disponible;
    private Integer servicio;
    private String tamano;

    public ParqueaderoSummary() {
    }

    public ParqueaderoSummary(Long id) {
        this.id = id;
    }

    public ParqueaderoSummary(Long id, String nave, Integer numero, Integer numeroEnAgrupador, Integer agrupador, String recinto, Boolean tribunales, String estado, Boolean disponible, Integer servicio, String tamano) {
        this.id = id;
        this.nave = nave;
        this.numero = numero;
        this.numeroEnAgrupador = numeroEnAgrupador;
        this.agrupador = agrupador;
        this.recinto = recinto;
        this.tribunales = tribunales;
        this.estado = estado;
        this.disponible = disponible;
        this.servicio = servicio;
        this.tamano = tamano;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNave() {
        return nave;
    }

    public void setNave(String nave) {
        this.nave = nave;
    }

    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    public Integer getNumeroEnAgrupador() {
        return numeroEnAgrupador;
    }

    public void setNumeroEnAgrupador(Integer numeroEnAgrupador) {
        this.numeroEnAgrupador = numeroEnAgrupador;
    }

    public Integer getAgrupador() {
        return agrupador;
    }

    public void setAgrupador(Integer agrupador) {
        this.agrupador = agrupador;
    }

    public String getRecinto() {
        return recinto;
    }

    public void setRecinto(String recinto) {
        this.recinto = recinto;
    }

    public Boolean getTribunales() {
        return tribunales;
    }

    public void setTribunales(Boolean tribunales) {
        this.tribunales = tribunales;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Boolean getDisponible() {
        return disponible;
    }

    public void setDisponible(Boolean disponible) {
        this.disponible = disponible;
    }

    public Integer getServicio() {
        return servicio;
    }

    public void setServicio(Integer servicio) {
        this.servicio = servicio;
    }

    public String getTamano() {
        return tamano;
    }

    public void setTamano(String tamano) {
        this.tamano = tamano;
    }

}
