package test3.ncxchile.cl.greenDAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private int rut;
    /** Not-null value. */
    private String dv;
    private String password;
    private String nombre;
    private String apellidoPaterno;
    private String apellidoMaterno;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, int rut, String dv, String password, String nombre, String apellidoPaterno, String apellidoMaterno) {
        this.id = id;
        this.rut = rut;
        this.dv = dv;
        this.password = password;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRut() {
        return rut;
    }

    public void setRut(int rut) {
        this.rut = rut;
    }

    /** Not-null value. */
    public String getDv() {
        return dv;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDv(String dv) {
        this.dv = dv;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidoPaterno() {
        return apellidoPaterno;
    }

    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    public String getApellidoMaterno() {
        return apellidoMaterno;
    }

    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

}
