package co.woofy.upload;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import co.woofy.upload.Marca;

import co.woofy.upload.MarcaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig marcaDaoConfig;

    private final MarcaDao marcaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        marcaDaoConfig = daoConfigMap.get(MarcaDao.class).clone();
        marcaDaoConfig.initIdentityScope(type);

        marcaDao = new MarcaDao(marcaDaoConfig, this);

        registerDao(Marca.class, marcaDao);
    }
    
    public void clear() {
        marcaDaoConfig.getIdentityScope().clear();
    }

    public MarcaDao getMarcaDao() {
        return marcaDao;
    }

}
