package co.woofy.upload;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import co.woofy.upload.Firma;
import co.woofy.upload.Acta;

import co.woofy.upload.FirmaDao;
import co.woofy.upload.ActaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig firmaDaoConfig;
    private final DaoConfig actaDaoConfig;

    private final FirmaDao firmaDao;
    private final ActaDao actaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        firmaDaoConfig = daoConfigMap.get(FirmaDao.class).clone();
        firmaDaoConfig.initIdentityScope(type);

        actaDaoConfig = daoConfigMap.get(ActaDao.class).clone();
        actaDaoConfig.initIdentityScope(type);

        firmaDao = new FirmaDao(firmaDaoConfig, this);
        actaDao = new ActaDao(actaDaoConfig, this);

        registerDao(Firma.class, firmaDao);
        registerDao(Acta.class, actaDao);
    }
    
    public void clear() {
        firmaDaoConfig.getIdentityScope().clear();
        actaDaoConfig.getIdentityScope().clear();
    }

    public FirmaDao getFirmaDao() {
        return firmaDao;
    }

    public ActaDao getActaDao() {
        return actaDao;
    }

}
