package co.woofy.upload;

import co.woofy.upload.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DETALLE_ESTADO_VISUAL.
 */
public class DetalleEstadoVisual {

    private Long id;
    private Boolean valor;
    private Boolean nombre;
    private String observacion;
    private long idVehiculo;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient DetalleEstadoVisualDao myDao;

    private Vehiculo vehiculo;
    private Long vehiculo__resolvedKey;


    public DetalleEstadoVisual() {
    }

    public DetalleEstadoVisual(Long id) {
        this.id = id;
    }

    public DetalleEstadoVisual(Long id, Boolean valor, Boolean nombre, String observacion, long idVehiculo) {
        this.id = id;
        this.valor = valor;
        this.nombre = nombre;
        this.observacion = observacion;
        this.idVehiculo = idVehiculo;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDetalleEstadoVisualDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getValor() {
        return valor;
    }

    public void setValor(Boolean valor) {
        this.valor = valor;
    }

    public Boolean getNombre() {
        return nombre;
    }

    public void setNombre(Boolean nombre) {
        this.nombre = nombre;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public long getIdVehiculo() {
        return idVehiculo;
    }

    public void setIdVehiculo(long idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

    /** To-one relationship, resolved on first access. */
    public Vehiculo getVehiculo() {
        long __key = this.idVehiculo;
        if (vehiculo__resolvedKey == null || !vehiculo__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            VehiculoDao targetDao = daoSession.getVehiculoDao();
            Vehiculo vehiculoNew = targetDao.load(__key);
            synchronized (this) {
                vehiculo = vehiculoNew;
            	vehiculo__resolvedKey = __key;
            }
        }
        return vehiculo;
    }

    public void setVehiculo(Vehiculo vehiculo) {
        if (vehiculo == null) {
            throw new DaoException("To-one property 'idVehiculo' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.vehiculo = vehiculo;
            idVehiculo = vehiculo.getId();
            vehiculo__resolvedKey = idVehiculo;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
