package co.woofy.upload;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import co.woofy.upload.EstadoVisual;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ESTADO_VISUAL.
*/
public class EstadoVisualDao extends AbstractDao<EstadoVisual, Long> {

    public static final String TABLENAME = "ESTADO_VISUAL";

    /**
     * Properties of entity EstadoVisual.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property RespuestaBinaria = new Property(2, Boolean.class, "respuestaBinaria", false, "RESPUESTA_BINARIA");
        public final static Property Habilitado = new Property(3, Boolean.class, "habilitado", false, "HABILITADO");
        public final static Property Tipo = new Property(4, Integer.class, "tipo", false, "TIPO");
    };

    private DaoSession daoSession;


    public EstadoVisualDao(DaoConfig config) {
        super(config);
    }
    
    public EstadoVisualDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ESTADO_VISUAL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NOMBRE' TEXT," + // 1: nombre
                "'RESPUESTA_BINARIA' INTEGER," + // 2: respuestaBinaria
                "'HABILITADO' INTEGER," + // 3: habilitado
                "'TIPO' INTEGER);"); // 4: tipo
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ESTADO_VISUAL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EstadoVisual entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(2, nombre);
        }
 
        Boolean respuestaBinaria = entity.getRespuestaBinaria();
        if (respuestaBinaria != null) {
            stmt.bindLong(3, respuestaBinaria ? 1l: 0l);
        }
 
        Boolean habilitado = entity.getHabilitado();
        if (habilitado != null) {
            stmt.bindLong(4, habilitado ? 1l: 0l);
        }
 
        Integer tipo = entity.getTipo();
        if (tipo != null) {
            stmt.bindLong(5, tipo);
        }
    }

    @Override
    protected void attachEntity(EstadoVisual entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public EstadoVisual readEntity(Cursor cursor, int offset) {
        EstadoVisual entity = new EstadoVisual( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nombre
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // respuestaBinaria
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // habilitado
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4) // tipo
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EstadoVisual entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRespuestaBinaria(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setHabilitado(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setTipo(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(EstadoVisual entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(EstadoVisual entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
