package co.woofy.upload;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FIRMA.
 */
public class Firma {

    private Long id;
    private String FirmaAutoridad;
    private String FirmaGruero;

    public Firma() {
    }

    public Firma(Long id) {
        this.id = id;
    }

    public Firma(Long id, String FirmaAutoridad, String FirmaGruero) {
        this.id = id;
        this.FirmaAutoridad = FirmaAutoridad;
        this.FirmaGruero = FirmaGruero;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirmaAutoridad() {
        return FirmaAutoridad;
    }

    public void setFirmaAutoridad(String FirmaAutoridad) {
        this.FirmaAutoridad = FirmaAutoridad;
    }

    public String getFirmaGruero() {
        return FirmaGruero;
    }

    public void setFirmaGruero(String FirmaGruero) {
        this.FirmaGruero = FirmaGruero;
    }

}
