package co.woofy.upload;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INSTITUCION.
 */
public class Institucion {

    private Long id;
    private Integer idExterno;
    private String nombre;
    private String tipo;

    public Institucion() {
    }

    public Institucion(Long id) {
        this.id = id;
    }

    public Institucion(Long id, Integer idExterno, String nombre, String tipo) {
        this.id = id;
        this.idExterno = idExterno;
        this.nombre = nombre;
        this.tipo = tipo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdExterno() {
        return idExterno;
    }

    public void setIdExterno(Integer idExterno) {
        this.idExterno = idExterno;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

}
