package co.woofy.upload;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_NAME.
 */
public class UserName {

    private Long id;
    private Long Rut;
    private String UserName;

    public UserName() {
    }

    public UserName(Long id) {
        this.id = id;
    }

    public UserName(Long id, Long Rut, String UserName) {
        this.id = id;
        this.Rut = Rut;
        this.UserName = UserName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRut() {
        return Rut;
    }

    public void setRut(Long Rut) {
        this.Rut = Rut;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

}
