package co.woofy.upload;

import java.util.List;
import co.woofy.upload.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VEHICULO.
 */
public class Vehiculo {

    private Long id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient VehiculoDao myDao;

    private List<DetalleEstadoVisual> detalleEstadoVisual;

    public Vehiculo() {
    }

    public Vehiculo(Long id) {
        this.id = id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getVehiculoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<DetalleEstadoVisual> getDetalleEstadoVisual() {
        if (detalleEstadoVisual == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DetalleEstadoVisualDao targetDao = daoSession.getDetalleEstadoVisualDao();
            List<DetalleEstadoVisual> detalleEstadoVisualNew = targetDao._queryVehiculo_DetalleEstadoVisual(id);
            synchronized (this) {
                if(detalleEstadoVisual == null) {
                    detalleEstadoVisual = detalleEstadoVisualNew;
                }
            }
        }
        return detalleEstadoVisual;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetDetalleEstadoVisual() {
        detalleEstadoVisual = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
